# ===========================
# Pipeline configuration file
# Example: multi-corpus run
# ===========================

# Output directory (will be created if missing)
output: "testing/multi"

# Languages - ISO 639-3 language code, followed by the ISO 15924 script code
# e.g. "cat_Latn", "srb_Cryl", "zho_Hans"
l1: "Catalan"
l2: "cmn_Hani"

# Embedding model (choices: labse, comet, sonar)
model: "labse"
model_path: null

# Filtering thresholds
alignment_score: 0.75
langid_l1_prob: 0.5
langid_l2_prob: 0.5

# Steps to run at the merged stage
# Merged steps are filter dedup and normalise
steps:
  - filter
  - dedup
  - bifixer
  - normalise


bifixer_flags: ["--ignore_segmentation", "--ignore_duplicates"]

# Input corpora (each runs its own per-corpus steps first)
# per-corpus steps are input embeddings and langid
inputs:
  - name: "TED2020"
    type: "plain_text"
    # paths: ["testing/TED2020.ca-zh.ca", "testing/TED2020.ca-zh.zh"]
    start_from: /gpfs/scratch/bsc88/bsc088400/ParaCLEAN/testing/multi/TED2020.embeddings.tsv
    steps: ["langid"]

  - name: "QED"
    type: "plain_text"
    # paths: ["testing/QED.ca-zh.ca", "testing/QED.ca-zh.zh"]
    start_from: "testing/multi/QED.embeddings.tsv"   # resume from here instead of raw text
    steps: ["langid"]
